use super::command::*;
use crate::types::Screen;

#[derive(Debug, Clone)]
pub struct CommandContext {
    pub current_screen: Screen,
    pub has_selected_feed: bool,
    pub has_selected_alert: bool,
    pub has_selected_keyword: bool,
    pub discord_configured: bool,
    pub webhook_configured: bool,
    pub email_configured: bool,
}

impl Default for CommandContext {
    fn default() -> Self {
        Self {
            current_screen: Screen::Dashboard,
            has_selected_feed: false,
            has_selected_alert: false,
            has_selected_keyword: false,
            discord_configured: false,
            webhook_configured: false,
            email_configured: false,
        }
    }
}

pub static ALL_COMMANDS: &[Command] = &[
    Command {
        id: CommandId::OpenDashboard,
        canonical: "dashboard open",
        title: "Open Dashboard",
        description: "Navigate to the dashboard screen.",
        group: CommandGroup::Navigation,
        aliases: &["open dashboard", "go dashboard", "show dashboard"],
        keywords: &["dashboard", "home", "overview", "stats"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Dashboard),
    },
    Command {
        id: CommandId::OpenFeeds,
        canonical: "feeds open",
        title: "Open Feeds",
        description: "Navigate to the feeds screen.",
        group: CommandGroup::Navigation,
        aliases: &["open feeds", "go feeds", "show feeds", "feed list"],
        keywords: &["feeds", "sources", "subscriptions"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Feeds),
    },
    Command {
        id: CommandId::OpenAlerts,
        canonical: "alerts open",
        title: "Open Alerts",
        description: "Navigate to the alerts screen.",
        group: CommandGroup::Navigation,
        aliases: &["open alerts", "go alerts", "show alerts"],
        keywords: &["alerts", "notifications", "warnings"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Alerts),
    },
    Command {
        id: CommandId::OpenKeywords,
        canonical: "keywords open",
        title: "Open Keywords",
        description: "Navigate to the keywords screen.",
        group: CommandGroup::Navigation,
        aliases: &["open keywords", "go keywords", "show keywords"],
        keywords: &["keywords", "rules", "patterns", "watch terms"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Keywords),
    },
    Command {
        id: CommandId::OpenTags,
        canonical: "tags open",
        title: "Open Tags",
        description: "Navigate to the tags screen.",
        group: CommandGroup::Navigation,
        aliases: &["open tags", "go tags", "show tags"],
        keywords: &["tags", "labels", "categories"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Tags),
    },
    Command {
        id: CommandId::OpenIndicators,
        canonical: "indicators open",
        title: "Open Indicators",
        description: "Navigate to the indicators screen.",
        group: CommandGroup::Navigation,
        aliases: &[
            "open indicators",
            "go indicators",
            "show indicators",
            "iocs",
        ],
        keywords: &["indicators", "iocs", "threat intel"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Indicators),
    },
    Command {
        id: CommandId::OpenSettings,
        canonical: "settings open",
        title: "Open Settings",
        description: "Navigate to the settings screen.",
        group: CommandGroup::Navigation,
        aliases: &["open settings", "go settings", "show settings", "config"],
        keywords: &["settings", "config", "preferences", "options"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Settings),
    },
    Command {
        id: CommandId::OpenHelp,
        canonical: "help open",
        title: "Open Help",
        description: "Show the help overlay.",
        group: CommandGroup::Navigation,
        aliases: &["open help", "show help", "?"],
        keywords: &["help", "guide", "shortcuts", "keys"],
        availability: CommandAvailability::Always,
        action: CommandAction::OpenModal(ModalKind::Help),
    },
    Command {
        id: CommandId::Refresh,
        canonical: "refresh",
        title: "Refresh",
        description: "Refresh the current screen data.",
        group: CommandGroup::System,
        aliases: &["reload", "update", "sync"],
        keywords: &["refresh", "reload", "update", "sync", "fetch"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::Refresh),
    },
    Command {
        id: CommandId::Quit,
        canonical: "quit",
        title: "Quit",
        description: "Exit ThreatDeck.",
        group: CommandGroup::System,
        aliases: &["exit", "close", "shutdown"],
        keywords: &["quit", "exit", "close", "shutdown", "stop"],
        availability: CommandAvailability::Always,
        action: CommandAction::Quit,
    },
    Command {
        id: CommandId::FeedAdd,
        canonical: "feed add",
        title: "Add Feed",
        description: "Add a new feed source.",
        group: CommandGroup::Feed,
        aliases: &["add feed", "new feed", "create feed"],
        keywords: &["feed", "add", "new", "create", "source"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::FeedAdd),
    },
    Command {
        id: CommandId::FeedEditSelected,
        canonical: "feed edit selected",
        title: "Edit Selected Feed",
        description: "Edit the currently selected feed.",
        group: CommandGroup::Feed,
        aliases: &["edit feed", "modify feed"],
        keywords: &["feed", "edit", "modify", "update"],
        availability: CommandAvailability::WhenFeedSelected,
        action: CommandAction::Dispatch(AppAction::FeedEditSelected),
    },
    Command {
        id: CommandId::FeedCheckSelected,
        canonical: "feed check selected",
        title: "Check Selected Feed",
        description: "Manually fetch the selected feed.",
        group: CommandGroup::Feed,
        aliases: &["fetch feed", "refresh feed", "run feed"],
        keywords: &["feed", "check", "fetch", "refresh", "run"],
        availability: CommandAvailability::WhenFeedSelected,
        action: CommandAction::Dispatch(AppAction::FeedCheckSelected),
    },
    Command {
        id: CommandId::FeedCheckAll,
        canonical: "feed check all",
        title: "Check All Feeds",
        description: "Manually fetch all enabled feeds.",
        group: CommandGroup::Feed,
        aliases: &["fetch all", "refresh all", "run all feeds", "check feeds"],
        keywords: &["feed", "feeds", "check", "fetch", "refresh", "run", "all"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::FeedCheckAll),
    },
    Command {
        id: CommandId::FeedEnableSelected,
        canonical: "feed enable selected",
        title: "Enable Selected Feed",
        description: "Enable the currently selected feed.",
        group: CommandGroup::Feed,
        aliases: &["enable feed", "turn on feed"],
        keywords: &["feed", "enable", "turn on", "activate"],
        availability: CommandAvailability::WhenFeedSelected,
        action: CommandAction::Dispatch(AppAction::FeedEnableSelected),
    },
    Command {
        id: CommandId::FeedDisableSelected,
        canonical: "feed disable selected",
        title: "Disable Selected Feed",
        description: "Disable the currently selected feed.",
        group: CommandGroup::Feed,
        aliases: &["disable feed", "turn off feed"],
        keywords: &["feed", "disable", "turn off", "deactivate"],
        availability: CommandAvailability::WhenFeedSelected,
        action: CommandAction::Dispatch(AppAction::FeedDisableSelected),
    },
    Command {
        id: CommandId::FeedHealth,
        canonical: "feed health",
        title: "Feed Health",
        description: "Open the feed health dashboard.",
        group: CommandGroup::Feed,
        aliases: &["health dashboard", "feed status", "feed diagnostics"],
        keywords: &["feed", "health", "status", "diagnostics", "logs"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Logs),
    },
    Command {
        id: CommandId::AlertShowUnread,
        canonical: "alert unread",
        title: "Show Unread Alerts",
        description: "Filter alerts to show only unread.",
        group: CommandGroup::Alert,
        aliases: &["unread alerts", "new alerts"],
        keywords: &["alert", "unread", "new", "unseen"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::AlertShowUnread),
    },
    Command {
        id: CommandId::AlertShowCritical,
        canonical: "alert critical",
        title: "Show Critical Alerts",
        description: "Filter alerts to show only critical.",
        group: CommandGroup::Alert,
        aliases: &["critical alerts", "severe alerts"],
        keywords: &["alert", "critical", "severe", "high"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::AlertShowCritical),
    },
    Command {
        id: CommandId::AlertOpenSelected,
        canonical: "alert open selected",
        title: "Open Selected Alert",
        description: "Open the selected alert detail view.",
        group: CommandGroup::Alert,
        aliases: &["open alert", "view alert"],
        keywords: &["alert", "open", "view", "detail"],
        availability: CommandAvailability::WhenAlertSelected,
        action: CommandAction::Dispatch(AppAction::AlertMarkSelectedRead),
    },
    Command {
        id: CommandId::AlertMarkSelectedRead,
        canonical: "alert mark read",
        title: "Mark Selected Alert Read",
        description: "Mark the selected alert as read.",
        group: CommandGroup::Alert,
        aliases: &["mark read", "read alert"],
        keywords: &["alert", "mark", "read", "acknowledge"],
        availability: CommandAvailability::WhenAlertSelected,
        action: CommandAction::Dispatch(AppAction::AlertMarkSelectedRead),
    },
    Command {
        id: CommandId::AlertMarkSelectedUnread,
        canonical: "alert mark unread",
        title: "Mark Selected Alert Unread",
        description: "Mark the selected alert as unread.",
        group: CommandGroup::Alert,
        aliases: &["mark unread", "unread alert"],
        keywords: &["alert", "mark", "unread"],
        availability: CommandAvailability::WhenAlertSelected,
        action: CommandAction::Dispatch(AppAction::AlertMarkSelectedUnread),
    },
    Command {
        id: CommandId::AlertMarkVisibleRead,
        canonical: "alert mark visible read",
        title: "Mark Visible Alerts Read",
        description: "Mark all visible alerts as read.",
        group: CommandGroup::Alert,
        aliases: &["mark all read", "read all visible"],
        keywords: &["alert", "mark", "read", "all", "visible"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::AlertMarkVisibleRead),
    },
    Command {
        id: CommandId::AlertExportSelectedMarkdown,
        canonical: "alert export selected markdown",
        title: "Export Selected Alert (Markdown)",
        description: "Export the selected alert as Markdown.",
        group: CommandGroup::Alert,
        aliases: &["export alert", "markdown export"],
        keywords: &["alert", "export", "markdown", "md", "save"],
        availability: CommandAvailability::WhenAlertSelected,
        action: CommandAction::Dispatch(AppAction::AlertExportSelectedMarkdown),
    },
    Command {
        id: CommandId::AlertExportVisibleMarkdown,
        canonical: "alert export visible markdown",
        title: "Export Visible Alerts (Markdown)",
        description: "Export all visible alerts as Markdown.",
        group: CommandGroup::Alert,
        aliases: &["export all", "bulk export"],
        keywords: &["alert", "export", "markdown", "all", "visible", "bulk"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::AlertExportVisibleMarkdown),
    },
    // ── Workbench navigation: pane focus + context tabs (Ticket 10) ───────
    // Direct pane focus via the palette (there is no 1/2/3 key binding —
    // those are the app's global screen-switch hotkeys).
    Command {
        id: CommandId::AlertFocusList,
        canonical: "alert focus list",
        title: "Alerts: Focus List Pane",
        description: "Move keyboard focus to the alert list.",
        group: CommandGroup::Alert,
        aliases: &["focus alerts", "list pane"],
        keywords: &["alert", "focus", "list", "pane", "workbench"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertFocusList),
    },
    Command {
        id: CommandId::AlertFocusDetails,
        canonical: "alert focus details",
        title: "Alerts: Focus Details Pane",
        description: "Move keyboard focus to the alert details pane.",
        group: CommandGroup::Alert,
        aliases: &["focus details", "details pane"],
        keywords: &["alert", "focus", "details", "pane", "workbench"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertFocusDetails),
    },
    Command {
        id: CommandId::AlertFocusContext,
        canonical: "alert focus context",
        title: "Alerts: Focus Context Pane",
        description: "Move keyboard focus to the context panel.",
        group: CommandGroup::Alert,
        aliases: &["focus context", "context pane"],
        keywords: &["alert", "focus", "context", "pane", "workbench"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertFocusContext),
    },
    Command {
        id: CommandId::AlertTabIndicators,
        canonical: "alert tab indicators",
        title: "Alerts: Context Tab — Indicators",
        description: "Switch the context panel to the Indicators tab.",
        group: CommandGroup::Alert,
        aliases: &["indicators tab", "ioc tab"],
        keywords: &["alert", "tab", "indicators", "ioc", "context"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertTabIndicators),
    },
    Command {
        id: CommandId::AlertTabMetadata,
        canonical: "alert tab metadata",
        title: "Alerts: Context Tab — Metadata",
        description: "Switch the context panel to the Metadata tab.",
        group: CommandGroup::Alert,
        aliases: &["metadata tab", "json tab"],
        keywords: &["alert", "tab", "metadata", "json", "context"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertTabMetadata),
    },
    Command {
        id: CommandId::AlertTabEnrichment,
        canonical: "alert tab enrichment",
        title: "Alerts: Context Tab — Enrichment",
        description: "Switch the context panel to the Enrichment tab.",
        group: CommandGroup::Alert,
        aliases: &["enrichment tab"],
        keywords: &["alert", "tab", "enrichment", "context"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertTabEnrichment),
    },
    Command {
        id: CommandId::AlertTabHistory,
        canonical: "alert tab history",
        title: "Alerts: Context Tab — Triage History",
        description: "Switch the context panel to the Triage History tab.",
        group: CommandGroup::Alert,
        aliases: &["history tab", "triage tab"],
        keywords: &["alert", "tab", "history", "triage", "context"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertTabHistory),
    },
    Command {
        id: CommandId::AlertTabRaw,
        canonical: "alert tab raw",
        title: "Alerts: Context Tab — Raw Content",
        description: "Switch the context panel to the Raw Content tab.",
        group: CommandGroup::Alert,
        aliases: &["raw tab", "raw content"],
        keywords: &["alert", "tab", "raw", "content", "context"],
        availability: CommandAvailability::WhenScreen(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertTabRaw),
    },
    // ── Workbench triage (one-shot; need a selected alert) ────────────────
    Command {
        id: CommandId::AlertAcknowledge,
        canonical: "alert acknowledge",
        title: "Alerts: Acknowledge",
        description: "Acknowledge the selected alert.",
        group: CommandGroup::Alert,
        aliases: &["ack alert", "triage acknowledge"],
        keywords: &["alert", "acknowledge", "ack", "triage"],
        availability: CommandAvailability::WhenScreenAlertSelected(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertAcknowledge),
    },
    Command {
        id: CommandId::AlertInvestigate,
        canonical: "alert investigate",
        title: "Alerts: Start Investigating",
        description: "Mark the selected alert as investigating.",
        group: CommandGroup::Alert,
        aliases: &["investigate alert", "triage investigate"],
        keywords: &["alert", "investigate", "triage"],
        availability: CommandAvailability::WhenScreenAlertSelected(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertInvestigate),
    },
    Command {
        id: CommandId::AlertEscalate,
        canonical: "alert escalate",
        title: "Alerts: Escalate",
        description: "Escalate the selected alert.",
        group: CommandGroup::Alert,
        aliases: &["escalate alert", "triage escalate"],
        keywords: &["alert", "escalate", "triage"],
        availability: CommandAvailability::WhenScreenAlertSelected(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertEscalate),
    },
    Command {
        id: CommandId::AlertClose,
        canonical: "alert close",
        title: "Alerts: Close",
        description: "Close the selected alert (requires a disposition).",
        group: CommandGroup::Alert,
        aliases: &["close alert", "triage close"],
        keywords: &["alert", "close", "triage"],
        availability: CommandAvailability::WhenScreenAlertSelected(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertClose),
    },
    Command {
        id: CommandId::AlertReopen,
        canonical: "alert reopen",
        title: "Alerts: Reopen",
        description: "Reopen the selected alert.",
        group: CommandGroup::Alert,
        aliases: &["reopen alert", "triage reopen"],
        keywords: &["alert", "reopen", "triage"],
        availability: CommandAvailability::WhenScreenAlertSelected(Screen::Alerts),
        action: CommandAction::Dispatch(AppAction::AlertReopen),
    },
    Command {
        id: CommandId::FeedHealthExportMarkdown,
        canonical: "feed health export markdown",
        title: "Export Feed Health Report (Markdown)",
        description: "Export feed health status as Markdown.",
        group: CommandGroup::Feed,
        aliases: &["export feed health", "feed health markdown"],
        keywords: &["feed", "health", "export", "markdown", "status"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::FeedHealthExportMarkdown),
    },
    Command {
        id: CommandId::KeywordAdd,
        canonical: "keyword add",
        title: "Add Keyword",
        description: "Add a new keyword rule.",
        group: CommandGroup::Keyword,
        aliases: &["add keyword", "new keyword", "create keyword"],
        keywords: &["keyword", "add", "new", "create", "rule", "pattern"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::KeywordAdd),
    },
    Command {
        id: CommandId::KeywordEditSelected,
        canonical: "keyword edit selected",
        title: "Edit Selected Keyword",
        description: "Edit the currently selected keyword.",
        group: CommandGroup::Keyword,
        aliases: &["edit keyword", "modify keyword"],
        keywords: &["keyword", "edit", "modify", "update"],
        availability: CommandAvailability::WhenKeywordSelected,
        action: CommandAction::Dispatch(AppAction::KeywordEditSelected),
    },
    Command {
        id: CommandId::KeywordTestSelected,
        canonical: "keyword test selected",
        title: "Test Selected Keyword",
        description: "Test the selected keyword against sample input.",
        group: CommandGroup::Keyword,
        aliases: &["test keyword", "try keyword"],
        keywords: &["keyword", "test", "try", "sample", "match"],
        availability: CommandAvailability::WhenKeywordSelected,
        action: CommandAction::Dispatch(AppAction::KeywordTestSelected),
    },
    Command {
        id: CommandId::KeywordEnableSelected,
        canonical: "keyword enable selected",
        title: "Enable Selected Keyword",
        description: "Enable the currently selected keyword.",
        group: CommandGroup::Keyword,
        aliases: &["enable keyword", "turn on keyword"],
        keywords: &["keyword", "enable", "turn on", "activate"],
        availability: CommandAvailability::WhenKeywordSelected,
        action: CommandAction::Dispatch(AppAction::KeywordEnableSelected),
    },
    Command {
        id: CommandId::KeywordDisableSelected,
        canonical: "keyword disable selected",
        title: "Disable Selected Keyword",
        description: "Disable the currently selected keyword.",
        group: CommandGroup::Keyword,
        aliases: &["disable keyword", "turn off keyword"],
        keywords: &["keyword", "disable", "turn off", "deactivate"],
        availability: CommandAvailability::WhenKeywordSelected,
        action: CommandAction::Dispatch(AppAction::KeywordDisableSelected),
    },
    Command {
        id: CommandId::DoctorRun,
        canonical: "doctor run",
        title: "Run Doctor",
        description: "Run all doctor checks.",
        group: CommandGroup::Doctor,
        aliases: &["run doctor", "health check", "diagnose"],
        keywords: &["doctor", "health", "check", "diagnose", "diagnostics"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::DoctorRun),
    },
    Command {
        id: CommandId::DoctorTor,
        canonical: "doctor tor",
        title: "Check Tor",
        description: "Check Tor connectivity.",
        group: CommandGroup::Doctor,
        aliases: &["tor check", "onion health", "proxy check"],
        keywords: &["doctor", "tor", "onion", "proxy", "connectivity"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::DoctorTor),
    },
    Command {
        id: CommandId::DoctorDatabase,
        canonical: "doctor database",
        title: "Check Database",
        description: "Check database health.",
        group: CommandGroup::Doctor,
        aliases: &["db check", "sqlite check", "database health"],
        keywords: &["doctor", "database", "db", "sqlite", "health"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::DoctorDatabase),
    },
    Command {
        id: CommandId::DoctorNotifications,
        canonical: "doctor notifications",
        title: "Check Notifications",
        description: "Check notification routes.",
        group: CommandGroup::Doctor,
        aliases: &["notify check", "notification health", "route check"],
        keywords: &["doctor", "notifications", "notify", "routes", "health"],
        availability: CommandAvailability::Always,
        action: CommandAction::Dispatch(AppAction::DoctorNotifications),
    },
    Command {
        id: CommandId::NotifyTestDiscord,
        canonical: "notify test discord",
        title: "Test Discord",
        description: "Send a test notification to Discord.",
        group: CommandGroup::Notification,
        aliases: &["test discord", "discord test"],
        keywords: &["notify", "discord", "test", "webhook"],
        availability: CommandAvailability::WhenNotificationRouteConfigured(
            NotificationRouteKind::Discord,
        ),
        action: CommandAction::Dispatch(AppAction::NotifyTestDiscord),
    },
    Command {
        id: CommandId::NotifyTestWebhook,
        canonical: "notify test webhook",
        title: "Test Webhook",
        description: "Send a test notification to the configured webhook.",
        group: CommandGroup::Notification,
        aliases: &["test webhook", "webhook test"],
        keywords: &["notify", "webhook", "test", "http"],
        availability: CommandAvailability::WhenNotificationRouteConfigured(
            NotificationRouteKind::Webhook,
        ),
        action: CommandAction::Dispatch(AppAction::NotifyTestWebhook),
    },
    Command {
        id: CommandId::NotifyTestEmail,
        canonical: "notify test email",
        title: "Test Email",
        description: "Send a test email notification.",
        group: CommandGroup::Notification,
        aliases: &["test email", "email test", "smtp test"],
        keywords: &["notify", "email", "test", "smtp"],
        availability: CommandAvailability::WhenNotificationRouteConfigured(
            NotificationRouteKind::Email,
        ),
        action: CommandAction::Dispatch(AppAction::NotifyTestEmail),
    },
    Command {
        id: CommandId::NotifyOpenSettings,
        canonical: "notify open settings",
        title: "Open Notification Settings",
        description: "Open notification settings.",
        group: CommandGroup::Notification,
        aliases: &["notification settings", "notify settings"],
        keywords: &["notify", "settings", "config", "notifications"],
        availability: CommandAvailability::Always,
        action: CommandAction::Navigate(Screen::Settings),
    },
];

pub fn available_commands(ctx: &CommandContext) -> Vec<&'static Command> {
    ALL_COMMANDS
        .iter()
        .filter(|cmd| is_available(cmd, ctx))
        .collect()
}

pub(crate) fn is_available(cmd: &Command, ctx: &CommandContext) -> bool {
    match cmd.availability {
        CommandAvailability::Always => true,
        CommandAvailability::WhenFeedSelected => ctx.has_selected_feed,
        CommandAvailability::WhenAlertSelected => ctx.has_selected_alert,
        CommandAvailability::WhenKeywordSelected => ctx.has_selected_keyword,
        CommandAvailability::WhenNotificationRouteConfigured(kind) => match kind {
            NotificationRouteKind::Discord => ctx.discord_configured,
            NotificationRouteKind::Webhook => ctx.webhook_configured,
            NotificationRouteKind::Email => ctx.email_configured,
        },
        CommandAvailability::WhenScreen(screen) => ctx.current_screen == screen,
        CommandAvailability::WhenScreenAlertSelected(screen) => {
            ctx.current_screen == screen && ctx.has_selected_alert
        }
    }
}
